name: Release published
on:
  release:
    types: [published]
jobs:
  add-changelog:
    name: Add Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Add Changelog
        uses: vonage/github-actions/vonage-changelog@master
        env:
          CHANGELOG_AUTH_TOKEN: ${{ secrets.CHANGELOG_AUTH_TOKEN }}
          CHANGELOG_CATEGORY: Server SDK
          CHANGELOG_RELEASE_TITLE: vonage-python
          CHANGELOG_SUBCATEGORY: python
